model:
  cls_factor: 0.1
  gp_factor: 10
  temperature: 0.1
  num_sub_policies: 10
  num_chunks: 16
  operation_count: 2

data:
  name: cifar10
  train_size: 4_000
  batch_size: 128

  cutout: false
  download: false

optim:
  epochs:  30

  main_lr: 1e-4
  policy_lr: 1e-4

gpu: 0
seed: 1
